import { Test, TestingModule } from '@nestjs/testing';
import { SystemIntegrationDbHandlerService } from './system-integration-db-handler.service';
import { PrismaClientService } from 'src/external-modules/prisma-client/prisma-client.service';
import { SystemIntegrationDbQueryBuilderService } from './system-integration-db-query-builder.service';
import { mockPrismaClientService } from 'test/mocks/providers/mock_prisma_client';
import { IBuildRetrieveIntegrationListArgs } from './interfaces/query-builder-args.interfaces';
import { Prisma } from '@prisma/client';

describe('SystemIntegrationDbHandlerService', () => {
  let service: SystemIntegrationDbHandlerService;
  let prismaClient: PrismaClientService;
  // let systemIntegrationDbQueryBuilder: SystemIntegrationDbQueryBuilderService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        SystemIntegrationDbHandlerService,
        SystemIntegrationDbQueryBuilderService,
        { provide: PrismaClientService, useValue: mockPrismaClientService },
      ],
    }).compile();

    service = module.get<SystemIntegrationDbHandlerService>(
      SystemIntegrationDbHandlerService,
    );
    prismaClient = module.get<PrismaClientService>(PrismaClientService);
    // systemIntegrationDbQueryBuilder =
    //   module.get<SystemIntegrationDbQueryBuilderService>(
    //     SystemIntegrationDbQueryBuilderService,
    //   );
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  it('should be defined', () => {
    expect(service).toBeDefined();
  });

  describe('retrieveList', () => {
    it('should call prismaClient.integrationTemplate.findMany with the correct query generated by systemIntegrationDbQueryBuilder', async () => {
      const query: IBuildRetrieveIntegrationListArgs = {
        pg: 2,
        perPage: 20,
        templateSrcSystem: 'ezCater',
        templateTargetSystem: 'Nutshell',
      };
      const expectedQueryWithoutInclude: Prisma.IntegrationTemplateFindManyArgs =
        {
          take: 20,
          skip: 20,
          where: {
            srcSystem: 'ezCater',
            targetSystem: 'Nutshell',
          },
        };
      const expectedRecords = [{ id: 1 } as any, { id: 2 }];

      jest
        .spyOn(prismaClient.integrationTemplate, 'findMany')
        .mockResolvedValue(expectedRecords);

      const result = await service.retrieveList(query);

      expect(prismaClient.integrationTemplate.findMany).toHaveBeenCalledWith({
        ...expectedQueryWithoutInclude,
        include: {
          requirements: true,
        },
      });
      expect(result).toEqual(expectedRecords);
    });

    it('should handle empty query and use default values', async () => {
      const expectedQueryWithoutInclude: Prisma.IntegrationTemplateFindManyArgs =
        {
          take: 10,
        };
      const expectedRecords = [{ id: 1 } as any, { id: 2 }];

      jest
        .spyOn(prismaClient.integrationTemplate, 'findMany')
        .mockResolvedValue(expectedRecords);

      const result = await service.retrieveList();

      expect(prismaClient.integrationTemplate.findMany).toHaveBeenCalledWith({
        ...expectedQueryWithoutInclude,
        include: {
          requirements: true,
        },
      });
      expect(result).toEqual(expectedRecords);
    });

    it('should handle query with only templateSrcSystem', async () => {
      const query: IBuildRetrieveIntegrationListArgs = {
        templateSrcSystem: 'ezCater',
      };
      const expectedQueryWithoutInclude: Prisma.IntegrationTemplateFindManyArgs =
        {
          take: 10,
          where: {
            srcSystem: 'ezCater',
          },
        };
      const expectedRecords = [{ id: 1 } as any, { id: 2 }];

      jest
        .spyOn(prismaClient.integrationTemplate, 'findMany')
        .mockResolvedValue(expectedRecords);

      const result = await service.retrieveList(query);

      expect(prismaClient.integrationTemplate.findMany).toHaveBeenCalledWith({
        ...expectedQueryWithoutInclude,
        include: {
          requirements: true,
        },
      });
      expect(result).toEqual(expectedRecords);
    });

    it('should handle query with only templateTargetSystem', async () => {
      const query: IBuildRetrieveIntegrationListArgs = {
        templateTargetSystem: 'Nutshell',
      };
      const expectedQueryWithoutInclude: Prisma.IntegrationTemplateFindManyArgs =
        {
          take: 10,
          where: {
            targetSystem: 'Nutshell',
          },
        };
      const expectedRecords = [{ id: 1 } as any, { id: 2 }];

      jest
        .spyOn(prismaClient.integrationTemplate, 'findMany')
        .mockResolvedValue(expectedRecords);

      const result = await service.retrieveList(query);

      expect(prismaClient.integrationTemplate.findMany).toHaveBeenCalledWith({
        ...expectedQueryWithoutInclude,
        include: {
          requirements: true,
        },
      });
      expect(result).toEqual(expectedRecords);
    });
  });
});
