import { Test, TestingModule } from '@nestjs/testing';
import { SystemIntegrationDbQueryBuilderService } from './system-integration-db-query-builder.service';
import queryBuilderUtilities from './utilities/query-builder-utilities';
import { Prisma } from '@prisma/client';
import { IBuildRetrieveIntegrationListArgs } from './interfaces/query-builder-args.interfaces';

jest.mock('./utilities/query-builder-utilities');

describe('SystemIntegrationDbQueryBuilderService', () => {
  let service: SystemIntegrationDbQueryBuilderService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [SystemIntegrationDbQueryBuilderService],
    }).compile();

    service = module.get<SystemIntegrationDbQueryBuilderService>(
      SystemIntegrationDbQueryBuilderService,
    );
  });

  it('should be defined', () => {
    expect(service).toBeDefined();
  });

  describe('buildRetrieveIntegrationsListQueryWithoutInclude (Integration Tests)', () => {
    it('should include the where clause generated by queryBuilderUtilities when templateSrcSystem is provided', () => {
      const queryInput: IBuildRetrieveIntegrationListArgs = {
        templateSrcSystem: 'ezCater',
      };
      const expectedWhereClause: Prisma.IntegrationTemplateWhereInput = {
        srcSystem: 'ezCater',
      };

      const result =
        service.buildRetrieveIntegrationsListQueryWithoutInclude(queryInput);

      expect(
        queryBuilderUtilities.buildRetrieveIntegrationTemplatesListWhereClause,
      ).toHaveBeenCalledWith(queryInput);
      expect(result.where).toEqual(expectedWhereClause);
    });

    it('should include the where clause generated by queryBuilderUtilities when templateTargetSystem is provided', () => {
      const queryInput: IBuildRetrieveIntegrationListArgs = {
        templateTargetSystem: 'Nutshell',
      };
      const expectedWhereClause: Prisma.IntegrationTemplateWhereInput = {
        targetSystem: 'Nutshell',
      };

      const result =
        service.buildRetrieveIntegrationsListQueryWithoutInclude(queryInput);

      expect(
        queryBuilderUtilities.buildRetrieveIntegrationTemplatesListWhereClause,
      ).toHaveBeenCalledWith(queryInput);
      expect(result.where).toEqual(expectedWhereClause);
    });

    it('should include the where clause generated by queryBuilderUtilities when both templateSrcSystem and templateTargetSystem are provided', () => {
      const queryInput: IBuildRetrieveIntegrationListArgs = {
        templateSrcSystem: 'ezCater',
        templateTargetSystem: 'Nutshell',
      };
      const expectedWhereClause: Prisma.IntegrationTemplateWhereInput = {
        srcSystem: 'ezCater',
        targetSystem: 'Nutshell',
      };

      const result =
        service.buildRetrieveIntegrationsListQueryWithoutInclude(queryInput);

      expect(
        queryBuilderUtilities.buildRetrieveIntegrationTemplatesListWhereClause,
      ).toHaveBeenCalledWith(queryInput);
      expect(result.where).toEqual(expectedWhereClause);
    });

    it('should not include the where clause when neither templateSrcSystem nor templateTargetSystem is provided', () => {
      const queryInput = {};

      const result =
        service.buildRetrieveIntegrationsListQueryWithoutInclude(queryInput);

      expect(
        queryBuilderUtilities.buildRetrieveIntegrationTemplatesListWhereClause,
      ).not.toHaveBeenCalled();
      expect(result.where).toBeUndefined();
    });

    it('should pass the correct queryInput to queryBuilderUtilities', () => {
      const queryInput: IBuildRetrieveIntegrationListArgs = {
        pg: 2,
        perPage: 20,
        templateSrcSystem: 'ezCater',
        templateTargetSystem: 'Nutshell',
      };

      service.buildRetrieveIntegrationsListQueryWithoutInclude(queryInput);

      expect(
        queryBuilderUtilities.buildRetrieveIntegrationTemplatesListWhereClause,
      ).toHaveBeenCalledWith({
        templateSrcSystem: 'ezCater',
        templateTargetSystem: 'Nutshell',
      });
    });
  });
});
