mutation createSubscription(
  $subscriberId: String!
  $eventKey: String!
  $catererId: String!
) {
  createSubscription(
    subscriptionParams: {
      subscriberId: $subscriberId
      eventKey: $eventKey
      eventEntity: Order
      parentEntity: Caterer
      parentId: $catererId
    }
  ) {
    subscription {
      parentEntity
      parentId
      eventKey
      eventEntity
    }
  }
}
